### ISSUE TITLE
Ändpunkt för att hämta customer log info

### ISSUE THREAD

**Issue by datalowe** [datalowe/pattern-backend#20]
Frontend har önskemål om att vi lägger till:

`/api/users/{id}/logs` ska skicka tillbaka alla loggar (alltså en array av individuella loggar). (vore nice-to-have här att skicka med stadsnamn utöver stadsid här, om jag förstod @fahlstrm rätt) 

(`/api/logs/` ska vara kvar. `/api/logs/{id}` ska finnas kvar, vore nice-to-have om den dessutom skickar med extra information om loggen, typ vilken stad och vilken användare, fast är lite nice to have. om vi kan/ska göra det så fråga @fahlstrm om mer info om just vad som behövs)

**Comment by joki20** [comment]
/api/users/{id}/logs (med ett g) tillagt

**Comment by datalowe** [comment]
Se PR #23 för mer info om `/api/users/{id}/logs` som den funkar just nu. Nice-to-have med att inkludera stadsnamn är inte inlagt för tillfället, vi får se om det finns tid/är värt tiden att fixa det. Lämnar issue öppen så länge.

**Comment by datalowe** [comment]
Frida har sagt för tillfället att frontend löser saker med 'nice-to-haves' och backend kan vara som den är vad gäller ändpunkter/vad som returneras, för admins del. Se även relaterad issue #26 som stängdes av samma orsak.
